language: node_js
before_script:
  - TRAVIS_FROM_BRANCH='travis_from_branch'
  - git branch $TRAVIS_FROM_BRANCH
  - git checkout $TRAVIS_FROM_BRANCH
  - git fetch origin master
  - git checkout -qf FETCH_HEAD
  - git checkout master
  - git checkout $TRAVIS_FROM_BRANCH
script: yarn lint index.js
after_failure:
  - gem install bundle
  - bundle install --without local
  - git diff --name-only --diff-filter=ACMR master | grep js | xargs yarn lint | bundle exec checkstyle_filter-git diff master | bundle exec saddler report --require saddler/reporter/github --reporter Saddler::Reporter::Github::PullRequestReviewComment
